version: '3'  # this is compose file format version number

services:
  web:      # this is what we choose to call our first single service
    build: .      #tells compose where to find the dockerfile to use to build our image
    ports:        # this line and next replaces the -p 3000:3000 used to map ports
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app      # this is same as in docker run -v ${PWD}:/usr/src/app
    env_file: 
      - .env/development/web
      - .env/development/database
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
  
  webpack-dev-server:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/usr/src/app
    env_file: 
      - .env/development/web
      - .env/development/database
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  selenium-chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"

  redis:
    image: redis

  database:
    image: postgres
    env_file: 
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data: